# Generated by Django 4.1 on 2024-03-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0002_addauthor_addtag_addquote"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AddAuthor",
        ),
        migrations.RemoveField(
            model_name="addquote",
            name="author",
        ),
        migrations.RemoveField(
            model_name="addquote",
            name="tags",
        ),
        migrations.DeleteModel(
            name="AddTag",
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name="AddQuote",
        ),
    ]
